
package pt.ist.fenixedu.bpi.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BPISyncWebServiceService", targetNamespace = "http://webservice.bpi.fenixedu.ist.pt/", wsdlLocation = "https://fenix.tecnico.ulisboa.pt/web-services/bpiIntegration?wsdl")
public class BPISyncWebServiceService
    extends Service
{

    private final static URL BPISYNCWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BPISYNCWEBSERVICESERVICE_EXCEPTION;
    private final static QName BPISYNCWEBSERVICESERVICE_QNAME = new QName("http://webservice.bpi.fenixedu.ist.pt/", "BPISyncWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://fenix.tecnico.ulisboa.pt/web-services/bpiIntegration?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPISYNCWEBSERVICESERVICE_WSDL_LOCATION = url;
        BPISYNCWEBSERVICESERVICE_EXCEPTION = e;
    }

    public BPISyncWebServiceService() {
        super(__getWsdlLocation(), BPISYNCWEBSERVICESERVICE_QNAME);
    }

    public BPISyncWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPISYNCWEBSERVICESERVICE_QNAME, features);
    }

    public BPISyncWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, BPISYNCWEBSERVICESERVICE_QNAME);
    }

    public BPISyncWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPISYNCWEBSERVICESERVICE_QNAME, features);
    }

    public BPISyncWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BPISyncWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BPISyncWebService
     */
    @WebEndpoint(name = "BPISyncWebServicePort")
    public BPISyncWebService getBPISyncWebServicePort() {
        return super.getPort(new QName("http://webservice.bpi.fenixedu.ist.pt/", "BPISyncWebServicePort"), BPISyncWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPISyncWebService
     */
    @WebEndpoint(name = "BPISyncWebServicePort")
    public BPISyncWebService getBPISyncWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.bpi.fenixedu.ist.pt/", "BPISyncWebServicePort"), BPISyncWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPISYNCWEBSERVICESERVICE_EXCEPTION!= null) {
            throw BPISYNCWEBSERVICESERVICE_EXCEPTION;
        }
        return BPISYNCWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
